export const ApplicantApi = [
  {
    id: 1,
    photo: "./logo192.png",
    fname: "Aabhash",
    lname: "Shahi",
    email: "Aabhashshahi@gmail.com",
    phone: "9810589111",
    position: "UI/UX",
    Experience: "8Months",
    select: "Mid",
  },
  {
    id: 2,
    photo: "./logo192.png",
    fname: "Subash",
    lname: "Budhathoki",
    email: "subashBudhathoki72@gmail.com",
    phone: "9810589234",
    position: "React Js",
    Experience: "6Months",
    select: "Junior",
  },
  {
    id: 3,
    photo: "./logo192.png",
    fname: "Anish",
    lname: "Karki",
    email: "AnishKarki@gmail.com",
    phone: "9810589222",
    position: "QA",
    Experience: "4Months",
    select: "Junior",
  },
  {
    id: 4,
    photo: "./logo192.png",
    fname: "Sudip",
    lname: "Shrestha",
    email: "Sudipshrestha100@gmail.com",
    phone: "9810589333",
    position: "Dot Net",
    Experience: "6Months",
    select: "Mid",
  },
  {
    id: 5,
    photo: "./logo192.png",
    fname: "Bishal",
    lname: "Shrestha",
    email: "Bishalshrestha1001@gmail.com",
    phone: "9810589222",
    position: "QA",
    Experience: "6Months",
    select: "Junior",
  },
  {
    id: 6,
    photo: "./logo192.png",
    fname: "Pratik",
    lname: "Khadka",
    email: "Pratikkhadka777@gmail.com",
    phone: "9810589777",
    position: "React js",
    Experience: "6Months",
    select: "Mid",
  },
  {
    id: 7,
    photo: "./logo192.png",
    fname: "Bibek",
    lname: "Shakya",
    email: "BibekShakya04@gmail.com",
    phone: "9810589881",
    position: "Dot Net",
    Experience: "6Months",
    select: "Senior",
  },
];

export const CandidateApi = [
  {
    id: 1,
    photo: "./logo192.png",
    fname: "Aabhash",
    lname: "Shahi",
    email: "Aabhashshahi@gmail.com",
    phone: "9810589111",
    position: "UI/UX",
    Experience: "8Months",
    select: "Mid",
  },
  {
    id: 2,
    photo: "./logo192.png",
    fname: "Subash",
    lname: "Budhathoki",
    email: "subashBudhathoki72@gmail.com",
    phone: "9810589234",
    position: "React Js",
    Experience: "6Months",
    select: "Junior",
  },
  {
    id: 3,
    photo: "./logo192.png",
    fname: "Anish",
    lname: "Karki",
    email: "AnishKarki@gmail.com",
    phone: "9810589222",
    position: "QA",
    Experience: "4Months",
    select: "Junior",
  },
  {
    id: 4,
    photo: "./logo192.png",
    fname: "Sudip",
    lname: "Shrestha",
    email: "Sudipshrestha100@gmail.com",
    phone: "9810589333",
    position: "Dot Net",
    Experience: "6Months",
    select: "Mid",
  },
];
export const blackListUserData = [
  {
    id: 8,
    photo: "./logo192.png",
    fname: "Sanjay",
    lname: "Shrestha",
    email: "Sanjayshrestha100@gmail.com",
    phone: "9810589334",
    position: "Dot Net",
    Experience: "6Months",
    select: "Mid",
    blackListReason: "Fake CV was provided.",
  },
];
